#! /bin/bash
#
# script name: VMMgr_Vars
# autor: Sylvain Girod ( uubu at gmx dot fr )
# version: 0.04
# description: Various Variables needed by VMMgr_Launcher
#
# Organiser et documenter les variables


# NEEDED VARS
#$IPMIHOST
#$IPMIPORT
#$VIRTPATH
#$SPICEIP
#$SPICEPORT
#$SPICEMODE
#$SPICEPWD

# Common Vars


### QEMU OPTIONS ###
# Note: all options can be overwrited in a specific template #


###Manque NUMA SMP QMP RAM


COMMON="-daemonize -no-user-config -nodefaults -msg timestamp=on"
CONFIG="-writeconfig $VMMGR_CONFIG_PATH/QEMU_CONFIGS/$NAME"
MACHINE="-machine q35,accel=kvm"
CPU64="-cpu qemu64"
CPUKVM="-cpu host,-hypervisor,+vmx,+x2apic,+kvm_pv_eoi,+kvm_pv_unhalt,+kvm_nopiodelay"

GLOBAL="-global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1"
PCI="-device pci-bridge,id=pci.0,chassis_nr=1"

### BIOS ###
BOOT="-boot menu=on,strict=off,splash=$VMMGR_DATA_PATH/UEFI/splash640.bmp,splash-time=5000"
BIOS="-bios /usr/share/qemu/bios-256k.bin -L /usr/share/qemu/"
#if [ ! -d $VIRTPATH/uefi/$NAME/ ]; then cp -r $VIRTPATH/uefi/SRC $VIRTPATH/uefi/$NAME; fi
#UEFI="-drive if=pflash,format=raw,file=$VIRTPATH/uefi/$NAME/OVMF_CODE.fd -global isa-debugcon.iobase=0x402 -debugcon file:$VIRTPATH/uefi/$NAME/$NAME.ovmf.log"

### Various Devices ###
USB="-device qemu-xhci"
MOUSE="-device virtio-mouse-pci"
KEYBOARD="-device virtio-keyboard-pci"
TABLET="-device virtio-tablet-pci"
IDEDVD="-drive if=none,id=DVD,readonly=on -device ide-cd,drive=DVD"
SCSIDVD="-device virtio-scsi-pci,id=scsi -drive if=none,id=DVD,readonly=on,format=raw -device scsi-cd,wwn=0x5000aa0102030405,bus=scsi0.0,channel=0,scsi-id=1,lun=0,drive=DVD,id=scsiDVD"
QXL="-device qxl-vga,id=qxl-video0,ram_size=67108864,vram_size=67108864"
###GUESTAGENT="-chardev socket,id=charchannel1,path=$VMMGR_CONFIG_PATH/guest_agent/f16x86_64.agent,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=2,chardev=charchannel1,id=channel1,name=org.qemu.guest_agent.0"
WATCHDOG="-device i6300esb,id=watchdog0 -watchdog-action none"
BALLOON="-device virtio-balloon-pci,id=balloon0"
RNG="-object rng-random,id=rng0,filename=/dev/random -device virtio-rng-pci,rng=rng0,max-bytes=1234,period=2000"
UNIXCLOCK="-realtime mlock=off -rtc base=utc,clock=vm,driftfix=slew -global kvm-pit.lost_tick_policy=discard"
WINDOWSCLOCK="-realtime mlock=off -rtc base=utc,clock=vm,driftfix=slew -global kvm-pit.lost_tick_policy=discard"
SOUND="-soundhw hda"
UUID="-uuid "$(cat /proc/sys/kernel/random/uuid)
NODISPLAY="-display none"
DISPLAYEGL="-display egl-headless"

### IPMI ###
IPMIDEV="-device ipmi-bmc-sim,id=bmc0 -chardev socket,id=ipmi0,host=$IPMIHOST,port=$IPMIPORT,reconnect=10 -device ipmi-bmc-extern,id=bmc0,chardev=ipmi0 -device isa-ipmi-kcs,bmc=bmc0,irq=5 -device isa-ipmi-bt,bmc=bmc0,irq0"

LXBASE="$COMMON $MACHINE $CPU $BIOS"
FAB="$COMMON $MACHINE $CPUKVM $CONFIG $BOOT $BIOS $PCI $USB $MOUSE $KEYBOARD $IDEDVD $QXL $WATCHDOG $BALLOON $RNG $UNIXCLOCK $SOUND $UUID $NODISPLAY"
