#! /bin/bash
#
# script name: VMMgr_Vars
# autor: Sylvain Girod ( uubu at gmx dot fr )
# version: 0.04
# description: Various Variables needed by VMMgr_Launcher
#
# Organiser et documenter les variables
# Common Vars
VIRTPATH=/home/sylvain/Virtualisation
SPICE_NET=10.10.10.0
TELNET_NET=10.10.11.0
QMP_NET=10.10.12.0
BRIDGE_TYPE=brctl

### QEMU OPTIONS ###
# Note: all options can be overwrited in a specific template #


Manque NUMA SMP TELNET SPICE QMP RAM


COMMON="-daemonize -display none -no-user-config -nodefaults -msg timestamp=on"
###CONFIG="-writeconfig $VIRTPATH/configs/$NAME"
MACHINE="-machine q35,accel=kvm"
CPU="-cpu host,-hypervisor,+vmx,+x2apic,+kvm_pv_eoi,+kvm_pv_unhalt,+kvm_nopiodelay"

GLOBAL="-global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1"
PCI="-device pci-bridge,id=pci.0,chassis_nr=1"

### BIOS ###
#BOOT="-boot menu=on,strict=off,splash=$VIRTPATH/uefi/splash640.bmp,splash-time=5000"
BIOS="-bios /usr/share/qemu/bios-256k.bin -L /usr/share/qemu/"
#if [ ! -d $VIRTPATH/uefi/$NAME/ ]; then cp -r $VIRTPATH/uefi/SRC $VIRTPATH/uefi/$NAME; fi
#UEFI="-drive if=pflash,format=raw,file=$VIRTPATH/uefi/$NAME/OVMF_CODE.fd -global isa-debugcon.iobase=0x402 -debugcon file:$VIRTPATH/uefi/$NAME/$NAME.ovmf.log"

### Various Devices ###
USB="-device qemu-xhci"
MOUSE="-device virtio-mouse-pci"
KEYBOARD="-device virtio-keyboard-pci"
TABLET="-device virtio-tablet-pci"
IDEDVD="-drive if=none,id=DVD,readonly=on -device ide-cd,drive=DVD"
SCSIDVD="-device virtio-scsi-pci,id=scsi -drive if=none,id=DVD,readonly=on,format=raw -device scsi-cd,wwn=0x5000aa0102030405,bus=scsi0.0,channel=0,scsi-id=1,lun=0,drive=DVD,id=scsiDVD"
QXL="-device qxl-vga,id=qxl-video0,ram_size=67108864,vram_size=67108864"
GUESTAGENT="-chardev socket,id=charchannel1,path=$VIRTPATH/disks/f16x86_64.agent,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=2,chardev=charchannel1,id=channel1,name=org.qemu.guest_agent.0"
WATCHDOG="-device i6300esb,id=watchdog0 -watchdog-action none"
BALLOON="-device virtio-balloon-pci,id=balloon0"
RNG="-object rng-random,id=rng0,filename=/dev/random -device virtio-rng-pci,rng=rng0,max-bytes=1234,period=2000"
UNIXCLOCK="-realtime mlock=off -rtc base=utc,clock=vm,driftfix=slew -global kvm-pit.lost_tick_policy=discard"
WINDOWSCLOCK="-realtime mlock=off -rtc base=utc,clock=vm,driftfix=slew -global kvm-pit.lost_tick_policy=discard"
SOUND="-soundhw hda"
UUID=$(cat /proc/sys/kernel/random/uuid)
NODISPLAY="display none"
DISPLAYEGL="display egl-headless"



### SPICE ###
SPICEAGENT="-device virtio-serial -chardev spicevmc,id=vdagent,debug=0,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0"
SPICEUSBREDIR="-device ich9-usb-ehci1,id=usb -device ich9-usb-uhci1,masterbus=usb.0,firstport=0,bus=pci.0,multifunction=on,addr=0x6 -device ich9-usb-uhci2,masterbus=usb.0,firstport=2,bus=pci.0,addr=0x6.0x1 -device ich9-usb-uhci3,masterbus=usb.0,firstport=4,bus=pci.0,addr=0x6.0x2 -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x7 -chardev spicevmc,id=charchannel0,name=vdagent -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=com.redhat.spice.0 -chardev spicevmc,id=charredir0,name=usbredir -device usb-redir,chardev=charredir0,id=redir0 -chardev spicevmc,id=charredir1,name=usbredir -device usb-redir,chardev=charredir1,id=redir1 -chardev spicevmc,id=charredir2,name=usbredir -device usb-redir,chardev=charredir2,id=redir2 -chardev spicevmc,id=charredir3,name=usbredir -device usb-redir,chardev=charredir3,id=redir3"
SPICESTREAM="-device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel1,id=channel1,name=org.spice-space.stream.0 -chardev spiceport,name=org.spice-space.stream.0,id=charchannel1"
SPICECAC="-device usb-ccid -chardev spicevmc,name=smartcard,id=ccid -device ccid-card-passthru,chardev=ccid"
SPICESHARE="-device virtserialport,bus=virtio-serial0.0,nr=3,chardev=charchannel2,id=channel2,name=org.spice-space.webdav.0 -chardev spiceport,name=org.spice-space.webdav.0,id=charchannel2"
SPICEVIRGL="-device virtio-vga,virgl=on -spice gl=on,unix,addr=/run/user/$(id -u)/spice.sock"
SPICELISTEN="addr=$SPICEIP"
SPICEPORT="port=$SPICEPORT"
SPICESPORT="tls-port=$SPICEPORT,tls-ciphers=tls1.2"
SPICEMOUSE="agent-mouse=on"
SPICEDTICKET="disable-ticketing"
SPICETICKET="password=$SPICEPWD"
$SPICECERTS="x509-dir=/etc/pki/VM/$name/,x509-key-password=,x509-cert-file=,x509-cacert-file=,509-dh-key-file="
$SPICECHANDEFAULT="$SPICEMODE-channel=default"
$SPICECHANMAIN="$SPICEMODE-channel=main"
$SPICECHANDISPLAY="$SPICEMODE-channel=display"
$SPICECHANINPUT="$SPICEMODE-channel=inputs"
$SPICECHANCURSOR"$SPICEMODE-channel=cursor"
$SPICECHANPLAYBACK="$SPICEMODE-channel=playback"
$SPICECHANRECORD="$SPICEMODE-channel=record"
$SPICECHANUSB="$SPICEMODE-channel=usbredir"
$SPICECOMPRESSION="image-compression=lz,jpeg-wan-compression=always,zlib-glz-wan-compression=always"
$SPICEPLAYBACKCOMP="playback-compression=on"
$SPICESTREAMVID="streaming-video=all"
$SPICEMIGRATION="seamless-migration=on"
$SPICEGL="gl=on,rendernode="
$SPICESASL="sasl"
$SPICETRANSPORT="ipv6"


### VNC ###



SPICE="-spice $SPCELISTEN,$SPICEPORT,$SPICEMOUSE,$SPICETICKET,$SPICECHANS,$SPICECOMPRESSION,$SPICEPLAYBACKCOMP,$SPICESTREAMVID,$SPICEMIGRATION $SPICE$SPICEAGENT $SPICEUSBREDIR $SPICESTREAM $SPICESHARE"
SPICESECURE="spice $SPCELISTEN,$SPICESPORT,$SPICESASL,$SPICECERTS,$SPICEMOUSE,$SPICEDTICKET,$SPICECHANS,$SPICECOMPRESSION,$SPICEPLAYBACKCOMP,$SPICESTREAMVID,$SPICEMIGRATION $SPICE$SPICEAGENT $SPICEUSBREDIR $SPICESTREAM $SPICESHARE"
