#! /bin/bash
#
# script name: VMMgr_Physical
# autor: Sylvain Girod ( uubu at gmx dot fr )
# version: 0.04
# description: function for physical hardware assignment
#
# Functions:
# SET_HID_PHYS: Find usb hid device (keyboard or mouse), and disconnect from the system
# SET_USB_STORAGE: Find usb storage device, and disconnect from the system
# SET_PHYS_HD: Add physical scsi/sata drive

# Function SET_HID_PHYS
# Description: Find usb hid device (keyboard or mouse), and disconnect from the system
# Args:
#   $1: "VENDORID:DEVICEID"
function SET_HID_PHYS() {
    DEVICE=$1
    DEVFULLNAME=$(ls /sys/bus/hid/drivers/hid-generic/ | grep ${DEVICE^^} | head -1)
    if [ "$DEVFULLNAME" != "" ]; then
        echo "$DEVFULLNAME" | sudo tee /sys/bus/hid/drivers/hid-generic/unbind 1>/dev/null
    fi
    read -r d1 BUS d2 DEVICE d3 <<< $(lsusb -d $DEVICE)
    ID=$(echo ${d3##*$1} | tr \  -  | tr \  - | tr -dc '[:alnum:]-\n\r')
    if [ "$BUS" ]; then
        SBUS=$(( 10#$BUS ))
        DEVICE=${DEVICE%:}
        SDEVICE=$(( 10#$DEVICE ))
        echo "-device usb-host,id=$ID,hostbus=$SBUS,hostaddr=$SDEVICE"
        sudo chown root:qemu /dev/bus/usb/$BUS/$DEVICE
    fi
}

# Function SET_USB_STORAGE
# Description: Find usb storage device, and disconnect from the system
# Args:
#   $1: "VENDORID:DEVICEID"
function SET_USB_STORAGE() {
    DEVICE=$1
    IFS=: read VENDID DEVID <<< $(echo "$DEVICE")
    VENDID=$(( 10#$VENDID ))
    DEVID=$(( 10#$DEVID ))
    FILTER="$VENDID/$DEVID"
    
    for DEVPATH in $(ls -1d /sys/bus/usb/drivers/usb-storage/[0-9A-F]*); do
        DEVFULLNAME=$(udevadm info --query=property $DEVPATH | grep PRODUCT | grep $FILTER)
        if [ "$DEVFULLNAME" ]; then
            echo $(basename $DEVPATH) | sudo tee $(dirname $DEVPATH)/unbind 1>/dev/null
            break
        fi
    done
    read -r d1 BUS d2 DEVICE d3 <<< $(lsusb -d $DEVICE)
    ID=$(echo ${d3##*$1} | tr \  -  | tr \  - | tr -dc '[:alnum:]-\n\r')
    if [ "$BUS" ]; then
        SBUS=$(( 10#$BUS ))
        DEVICE=${DEVICE%:}
        SDEVICE=$(( 10#$DEVICE ))
        echo "-device usb-host,id=$ID,hostbus=$SBUS,hostaddr=$SDEVICE"
    fi
}

# Function SET_PHYS_HD
# Description: Add physical scsi/sata drive
# Args:
# $1: device name (ex: /dev/sdd)
# $2: device number
function SET_PHYS_HD() {
    read d1 d2 d2 d4 MAJOR MINOR d5 <<< $(ls -l $1)
    if [ "$MAJOR" ]; then
        MAJOR=${MAJOR%,*}
        DEVNAME=$(ls -l /sys/dev/block/$MAJOR\:$MINOR/ | grep device)
        DEVNAME=${DEVNAME##*/}
        echo "-drive file=$1,format=raw,if=none,cache=none,id=hd${2,,} -device ich9-ahci,id=ahci${2,,} -device ide-hd,drive=hd${2,,},bus=ahci${2,,}.0"
    fi
}

# Function SET_USB_PHYS
# Description: Find usb device by specifyind syspath, and disconnect from the system
# Args:
#   $1: "VENDORID:DEVICEID"
#   $2: sysfs path
function SET_USB_PHYS() {
    DEVICE=$1
    DEVFULLNAME=$(ls ${2%/}/ | grep ${DEVICE^^} | head -1)
    if [ "$DEVFULLNAME" != "" ]; then
        echo "$DEVFULLNAME" | sudo tee ${2%/}/unbind 1>/dev/null
    fi
    IFS="
"
    for DEVENTRY in $(lsusb -d $DEVICE); do
        unset IFS
        read -r d1 BUS d2 DEVICE d3 <<< "$(echo $DEVENTRY)"
        ID=$(echo ${d3##*$1} | tr \  -  | tr -dc '[:alnum:]-\n\r')
        if [ "$BUS" ]; then
            SBUS=$(( 10#$BUS ))
            DEVICE=${DEVICE%:}
            SDEVICE=$(( 10#$DEVICE ))
            echo "-device usb-host,id=$ID$SBUS$SDEVICE,hostbus=$SBUS,hostaddr=$SDEVICE"
            sudo chown root:qemu /dev/bus/usb/$BUS/$DEVICE
        fi
    done
    unset IFS
}

# Function SET_DIF_USB
# Description: Connect usb device while vm at runtime
# Args:
#   $1: "VENDORID:DEVICEID"
#   $2: (optionnal) sysfs path
function SET_DIF_USB() {
    DEVICE=$1
    DEVFULLNAME=${2:-/sys/bus/hid/drivers/hid-generic/}
    DEVFULLNAME=$(ls ${DEVFULLNAME%/}/ | grep ${DEVICE^^} | head -1)
    if [ "$DEVFULLNAME" != "" ]; then
        echo "$DEVFULLNAME" | sudo tee ${2%/}/unbind 1>/dev/null
    fi
    IFS="
"
    for DEVENTRY in $(lsusb -d $DEVICE); do
        unset IFS
        read -r d1 BUS d2 DEVICE d3 <<< $(echo $DEVENTRY);
        ID=$(echo ${d3##*$1} | tr \  - | tr -dc '[:alnum:]-\n\r')
        if [ "$BUS" ]; then
            SBUS=$(( 10#$BUS ));
            DEVICE=${DEVICE%:};
            SDEVICE=$(( 10#$DEVICE ))
            sudo chown root:qemu /dev/bus/usb/$BUS/$DEVICE
            echo "device_add usb-host,id=$ID$SBUS$SDEVICE,hostbus=$SBUS,hostaddr=$SDEVICE"
        fi;
    done
    unset IFS
}

# Function SET_VF_NET
# Description: Connect an SR-IOV VF to the VM
# Args:
#  $1: VF number (ex: 17:10.1)
function SET_VF_NET() {
  DEVICE=$(lspci -vv  -s $1 | grep "IOMMU group:" | awk '{ print $3}')
  if [ -f $DEVICE ]; then
  sudo chown root:qemu /dev/vfio/$DEVICE
  sudo chmod 660 /dev/vfio/$DEVICE
  echo "-device vfio-pci,host=$1,multifunction=on"
}
