#! /bin/bash
#
# script name: VMMgr_Spice
# autor: Sylvain Girod ( uubu at gmx dot fr )
# version: 0.04
# description: SPICE Vars and Templates
#
SPICEAGENT="-device virtio-serial -chardev spicevmc,id=vdagent,debug=0,name=vdagent -device virtserialport,nr=1,id=channel0,chardev=vdagent,name=com.redhat.spice.0"
# retiré:                          -chardev spicevmc,id=charchannel0,name=vdagent   -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=com.redhat.spice.0
SPICEUSBREDIR="-device ich9-usb-ehci1,id=usb -device ich9-usb-uhci1,masterbus=usb.0,firstport=0,bus=pci.0,multifunction=on,addr=0x6 -device ich9-usb-uhci2,masterbus=usb.0,firstport=2,bus=pci.0,addr=0x6.0x1 -device ich9-usb-uhci3,masterbus=usb.0,firstport=4,bus=pci.0,addr=0x6.0x2 -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x7 -chardev spicevmc,id=charredir0,name=usbredir -device usb-redir,chardev=charredir0,id=redir0 -chardev spicevmc,id=charredir1,name=usbredir -device usb-redir,chardev=charredir1,id=redir1 -chardev spicevmc,id=charredir2,name=usbredir -device usb-redir,chardev=charredir2,id=redir2 -chardev spicevmc,id=charredir3,name=usbredir -device usb-redir,chardev=charredir3,id=redir3"


SPICESTREAM="-device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel1,id=channel1,name=org.spice-space.stream.0 -chardev spiceport,name=org.spice-space.stream.0,id=charchannel1"

SPICECAC="-device usb-ccid -chardev spicevmc,name=smartcard,id=ccid -device ccid-card-passthru,chardev=ccid"

SPICESHARE="-device virtserialport,bus=virtio-serial0.0,nr=3,chardev=charchannel2,id=channel2,name=org.spice-space.webdav.0 -chardev spiceport,name=org.spice-space.webdav.0,id=charchannel2"

SPICEVIRGL="-device virtio-vga,virgl=on -spice gl=on,unix,addr=/run/user/$(id -u)/spice.sock"

SPICELISTEN="addr=$SPICEIP"
SPICEUPORT="port=$SPICEPORT"
SPICESPORT="tls-port=$SPICEPORT,tls-ciphers=tls1.2"

SPICEMOUSE="agent-mouse=on"

SPICEDTICKET="disable-ticketing"
SPICETICKET="password=$SPICEPWD"

SPICECERTS="x509-dir=/etc/pki/VM/$name/,x509-key-password=,x509-cert-file=,x509-cacert-file=,509-dh-key-file="

SPICECHANDEFAULT="$SPICEMODE-channel=default"
SPICECHANMAIN="$SPICEMODE-channel=main"
SPICECHANDISPLAY="$SPICEMODE-channel=display"
SPICECHANINPUT="$SPICEMODE-channel=inputs"
SPICECHANCURSOR="$SPICEMODE-channel=cursor"
SPICECHANPLAYBACK="$SPICEMODE-channel=playback"
SPICECHANRECORD="$SPICEMODE-channel=record"
SPICECHANUSB="$SPICEMODE-channel=usbredir"

SPICECHANS="$SPICECHANDEFAULT,$SPICECHANMAIN,$SPICECHANDISPLAY,$SPICECHANINPUT,$SPICECHANCURSOR,$SPICECHANPLAYBACK,$SPICECHANPLAYBACK,$SPICECHANRECORD,$SPICECHANUSB"

SPICECOMPRESSION="image-compression=lz,jpeg-wan-compression=always,zlib-glz-wan-compression=always"
SPICEPLAYBACKCOMP="playback-compression=on"
SPICESTREAMVID="streaming-video=all"
SPICEMIGRATION="seamless-migration=on"
SPICEGL="gl=on,rendernode="
SPICESASL="sasl"
SPICETRANSPORT="ipv$SPICEIPVER"

### Templates for spice ###
# Not secure, easy for testing
SPICECLEAR="-spice $SPICELISTEN,$SPICEUPORT,$SPICETRANSPORT,$SPICEMOUSE,$SPICEDTICKET,$SPICECHANS,$SPICECOMPRESSION,$SPICEPLAYBACKCOMP,$SPICESTREAMVID,$SPICEMIGRATION $SPICEAGENT $SPICEUSBREDIR $SPICESTREAM $SPICESHARE"
# Secure, must be used in production
SPICESECURE="-spice $SPICELISTEN,$SPICESPORT,$SPICETRANSPORT,$SPICESASL,$SPICECERTS,$SPICEMOUSE,$SPICEDTICKET,$SPICECHANS,$SPICECOMPRESSION,$SPICEPLAYBACKCOMP,$SPICESTREAMVID,$SPICEMIGRATION $SPICEAGENT $SPICEUSBREDIR $SPICESTREAM $SPICESHARE $SPICECAC"
# Using virgl
SPICEGL="-spice $SPICELISTEN,$SPICEUPORT,$SPICETRANSPORT,$SPICEMOUSE,$SPICEGL,$SPICETICKET,$SPICECHANS,$SPICECOMPRESSION,$SPICEPLAYBACKCOMP,$SPICESTREAMVID,$SPICEMIGRATION $SPICEAGENT $SPICEUSBREDIR $SPICESTREAM $SPICESHARE $SPICEVIRGL"
