#! /bin/bash
#
# script name: VMMgr_CPU
# autor: Sylvain Girod ( uubu at gmx dot fr )
# version: 0.04
# description: CPU/SMP/NUMA/Machines templates Vars and Templates
#

### CPU templates ###
PORTABLE="kvm64"
CPUHOST="host,+x2apic,+kvm_pv_eoi,+kvm_pv_unhalt,+kvm_nopiodelay"
CPUNESTED="host,+vmx,+x2apic,+kvm_pv_eoi,+kvm_pv_unhalt,+kvm_nopiodelay"
CPUMAX="max,+x2apic,+kvm-asyncpf,+kvm-hint-dedicated,+kvm-mmu,+kvm-nopiodelay,+kvm-pv-eoi,+kvm-pv-ipi,+kvm-pv-tlb-flush,+kvm-pv-unhalt,+kvm-steal-time,+kvmclock,+kvmclock-stable-bit,+kvm_pv_eoi,+kvm_pv_unhalt,+kvm_nopiodelay"
CPUKVM="host,+x2apic,+kvm-asyncpf,+kvm-hint-dedicated,+kvm-mmu,+kvm-nopiodelay,+kvm-pv-eoi,+kvm-pv-ipi,+kvm-pv-tlb-flush,+kvm-pv-unhalt,+kvm-steal-time,+kvmclock,+kvmclock-stable-bit,+kvm_pv_eoi,+kvm_pv_unhalt,+kvm_nopiodelay"
CPUWIN="$CPUKVM,kvm=off,-hypervisor"

### SMP and NUMA ###

# 1 cpu
SMP1="-smp 1,cores=1,threads=1,sockets=1,maxcpus=1"
# 1 cpu HyperThreaded
SMP1HT=$(Set_Custom_SMP 1 1 $MEM)
# Map you physical CPU
SMPMAX=$(Map_SMP_1CPU $(Get_Total_CPUs) $MEM)
# Start with 4 cores
SMP4HT=$(Set_Custom_SMP 4 $MEM 1)
# start with 1 cpu, to max phycical cpu
SMP1TOMAX=$(Map_SMP_1CPU 1 $MEM)
# One numa node per core
SMPMAXNUMA=$(Map_SMP_1CPU $(Get_Total_CPUs) $MEM on)
# Start with 4 cpu, and create 4 numa nodes:
SMP4NUMA=$(Set_Custom_SMP 4 1 4 $MEM on)

### Machines ###
MACHINE35="q35,accel=kvm"
MACHINEMICROVM="microvm,-option-roms=off,pit=off,pic=off,rtc=off -no-reboot"
