#! /bin/bash
#
# script name: VMMgr_CPU
# autor: Sylvain Girod ( uubu at gmx dot fr )
# version: 0.04
# description: CPU/SMP/NUMA/Machines templates Vars and Templates
#

### CPU templates ###
PORTABLE="kvm64"
HOST="host,+x2apic,+kvm_pv_eoi,+kvm_pv_unhalt,+kvm_nopiodelay"
NESTED="host,+vmx,+x2apic,+kvm_pv_eoi,+kvm_pv_unhalt,+kvm_nopiodelay"
CPUMAX="max,+x2apic,+kvm-asyncpf,+kvm-hint-dedicated,+kvm-mmu,+kvm-nopiodelay,+kvm-pv-eoi,+kvm-pv-ipi,+kvm-pv-tlb-flush,+kvm-pv-unhalt,+kvm-steal-time,+kvmclock,+kvmclock-stable-bit,+kvm_pv_eoi,+kvm_pv_unhalt,+kvm_nopiodelay"


CPUTPL=$HOST

### SMP and NUMA ###
SMP1="-smp 1,cores=1,threads=1,sockets=1,maxcpus=1"
SMP1HT=$(Set_Custom_SMP 1 1)
MAX=$(Map_SMP_1CPU $(Get_Total_CPUs))
SMP4HT=$(Set_Custom_SMP 1 1)
SMP1TOMAX=$(Map_SMP_1CPU)
SMPMAXNUMA=$(Map_SMP_1CPU $(Get_Total_CPUs) on)
SMP4NUMA=$(Set_Custom_SMP 4 1 4 on)

### Machines ###
MACHINE35="q35,accel=kvm"
