#! /bin/bash
#
# script name: VMMgr_Devices
# autor: Sylvain Girod ( uubu at gmx dot fr )
# version: 0.04
# description: Various Devices needed by VMMgr_Launcher
#

### QEMU OPTIONS ###
# Note: all options can be overwrited in a specific template #


### we Daemonize, no default config, and timestamp in logs:
COMMON="-daemonize -no-user-config -nodefaults -msg timestamp=on"

### BOOT and BIOS
BOOT="-boot menu=on,strict=off,splash=$VMMGR_DATA_PATH/UEFI/splash640.bmp,splash-time=2000"
BIOS="-bios $(rpm -ql qemu-system-x86-core | grep "bios-256k.bin") -L $(dirname $(rpm -ql qemu-system-x86-core | grep "bios-256k.bin"))"

# Keyboard
KEY_LANG="-k fr"

# Mem alloc
MEMALLOC="--mem-prealloc"

### we disable S3 and S4:
#> i440fx only
#S34="-global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1"
#> q35
S34="-global ICH9-LPC.disable_s3=1 -global ICH9-LPC.disable_s4=1"

### Our first pci-bridge:
PCI="-device pci-bridge,id=pci.0,chassis_nr=1"

### except old OS like Windows 7, we use xhci usb3 controller:
USB="-device qemu-xhci,p2=15,p3=15"

### Mouse, Keyboard and Tablet using Virtio:
MOUSE="-device virtio-mouse-pci"
KEYBOARD="-device virtio-keyboard-pci"
TABLET="-device virtio-tablet-pci"

### DVDROM:
IDEDVD="-drive if=none,id=DVD,readonly=on -device ide-cd,drive=DVD"
SCSIDVD="-device virtio-scsi-pci,id=scsi0 -drive if=none,id=SDVD,readonly=on -device scsi-cd,wwn=0x5000aa0102030405,bus=scsi0.0,channel=0,scsi-id=1,lun=0,drive=SDVD,id=scsiDVD"

### First Graphical Card
QXL="-device qxl-vga,id=qxl-video0,vgamem_mb=32,ram_size_mb=64,vram_size_mb=64,max_outputs=1"

### for 3D display
### NOTE: not tested
VIRTIOGPU="device vfio-pci,host=00:00:02.0,x-vga=off,bus=pcie.0,addr=0x2,x-igd-opregion=on -device virtio-gpu-pci,virgl=on"

### Physical Graphical card
VFIOGPU="-device ioh3420,bus=pcie.0,addr=1c.0,multifunction=on,port=1,chassis=1,id=root.1 -device vfio-pci,host=17:00.0,bus=root.1,addr=00.0,multifunction=on,x-vga=off -device vfio-pci,host=17:00.1,bus=root.1,addr=00.1"

### Watchdog:
WATCHDOG="-device i6300esb,id=watchdog0 -watchdog-action none"

### Memory Balloon:
BALLOON="-device virtio-balloon-pci,id=balloon0"

### Random generator:
RNG="-object rng-random,id=rng0,filename=/dev/random -device virtio-rng-pci,rng=rng0,max-bytes=1234,period=2000"

### overcommit:
OVERCOMMIT="-overcommit cpu-pm=on -overcommit mem-lock=off"

### Unix Clock:
UNIXCLOCK="-rtc base=utc,clock=vm,driftfix=none -global kvm-pit.lost_tick_policy=discard"

### Windows Clock:
WINDOWSCLOCK="-rtc base=localtime,clock=vm,driftfix=none -global kvm-pit.lost_tick_policy=discard"

### Sound card
#> -soundhw is deprecated
#SOUND="-soundhw hda"
SOUND="-device intel-hda -device hda-duplex"
AUDIOSPICE="-audiodev driver=spice,id=audio1"

### No Display, used when we access to vm using vnc or spice:
NODISPLAY="-display none"

### for egl display:
DISPLAYEGL="-display egl-headless"

### vmgenid device:
VMGENID="-device vmgenid"

### pvpanic:
PANIC="-device pvpanic"

### vmcoreinfo
VMCORE="-device vmcoreinfo"

### TPM2
TPM2="-chardev socket,id=chrtpm,path=/var/lib/VMMGR/TPM2/$NAME.sock -tpmdev emulator,id=tpm2,chardev=chrtpm -device tpm-tis,tpmdev=tpm2"

### ccid

### fw_cfg
FW="-fw_cfg name=opt/GuestInfo,file=$VMMGR_DATA_PATH/VM_CONFIGS/$VMCONF"


### DEVICE TEMPLATES ###
LINUXBASE="$COMMON $BOOT $S34 $PCI $USB $MOUSE $KEYBOARD $TABLET $IDEDVD $QXL $WATCHDOG $BALLOON $RNG $OVERCOMMIT $UNIXCLOCK $NODISPLAY $VMGENID $PVPANIC $VMCORE $FW"
WINDOWSBASE="$COMMON $BOOT S34 $PCI $USB $MOUSE $KEYBOARD $IDEDVD $QXL $WATCHDOG $BALLOON $RNG $OVERCOMMIT $WINDOWSCLOCK $NODISPLAY $VMGENID $TPM2"

### This allow to dedicate a physical graphical card, See: https://github.com/uubufr/VMMgr/wiki/3.9---Assign-Physical-hardware
### we also remove all unsigned virtio driver
WINDOWSPHYSICAL="$COMMON $MEMALLOC $BOOT $S34 $PCI $USB $TABLET $IDEDVD $VFIOGPU $WATCHDOG $OVERCOMMIT $WINDOWSCLOCK $SOUND $VMGENID $NODISPLAY $TPM2"
