#! /bin/bash
#
# script name: %%NAME%%
# autor: Sylvain Girod ( uubu at gmx dot fr )
# version: 0.02
# description: Template for %%NAME%%
GROUP=""
NAME="%%NAME%%"         # Unique Name
MEM="1"                 # Initial Mem Size, in GB
MAXMEM="1"               # OPTIONAL: Max Allowed mem (defaut: $MEM * 2)

### Disks ###

DISKPATH="/mnt/disks/%%NAME%%/"

## Note: At least 1 First disk is needed, Defaut: Virtio Disk, but if iscsi is defined and not virtio, use iscsi as first disk only
mVDISKSIZE=""             # First virtio Disk Size. Defaut: 2GB
mSDISKSIZE=""            # OPTIONAL: First iscsi Disk Size. Defaut: 2GB
## Additionnals Disks
sVDISKNUMBER=""           # OPTIONAL: number of additionals Virtio Disks
sVDISKSIZE=""             # OPTIONAL: Size for optionals Virtio Disks
sSDISKNUMBER=""           # OPTIONAL: number of additionals ISCSI Disks
sSDISKSIZE=""             # OPTIONAL: Size for optionals ISCSI Disks

## you can set individual disk in calling function manually:
# Set_Disk virtio 50G Disk1
# Set_Disk iscsi 20G /mnt/idisks/%%NAME%%-disk2

### Network ###
# Set_NetDev <bridge> <number of taps>
# Set_NetDev swvpl-main 2
# Set_NetDev swvpl-admin 1


### choose Qemu machine Template:
New_Network swvpl-spice "6|2a01:e0a:278:9831::|64" "2a01:e0a:278:9831::10|2a01:e0a:278:9831::FFFF" 2a01:e0a:278:9831::1
SPICE=on
SPICEIP=swvpl-spice
SPICETYPE=bridge
SPICETPL=SPICESECURE

QEMU_TEMPLATE=$FAB

###env for spice:
EMU_AUDIO_DRV=spice
SPICE_DEBUG_ALLOW_MC=0
