#! /bin/bash
#
# script name: %%NAME%%
# autor: Sylvain Girod ( uubu at gmx dot fr )
# version: 0.02
# description: Template for %%NAME%%
GROUP="test"
TAGS="worstations dev"
ORDER="100"
STARTWAIT=30    # délai en seconde avant de démarrer cette vm
STARTWAIT=ok # on fait un test nous pour savoir si muti-users.target a été atteind dans la VM précédente
STARTIF="systemctl -machine xxxxx status mariadb"   # Commande utilisée pour vérifier quand démarrer la VM, c'est utilisé avec order
STOPIF=""       # Commande utilisée pour vérifier quand stopper la VM
STOPWAIT=1      # Plus simple, on arrête qu'une fois la précédente a été arrêtée

NAME="%%NAME%%"
MEM=1
MAXMEM=1
SLOT=2
CPU=HOST
SMPTPL=MAX

BIOSTYPE="SECURE"

### Disks ###
IOTHREADS=1
DISKPATH="/run/media/sylvain/STORAGE/4M/$NAME"
Virtio_Disk[0]="1 8G $DISKPATH"

DISKPATH="/run/media/sylvain/STORAGE/4M/$NAME/scsi/"
Scsi_Disk[0]="200 1G $DISKPATH"



### choose Qemu machine Template:
New_Network swvpl-spice "6|2a01:e0a:278:9831::|64" "2a01:e0a:278:9831::10|2a01:e0a:278:9831::FFFF" 2a01:e0a:278:9831::1
SPICE=on
SPICEIP=swvpl-spice
SPICETYPE=bridge
SPICETPL=SPICESECURE

New_Network swvpl-telnet "6|2a01:e0a:278:9832::|64" "2a01:e0a:278:9832::10|2a01:e0a:278:9832::FFFF" 2a01:e0a:278:9832::1
TELNET=on
TELNETIP=swvpl-telnet
TELNETTYPE=bridge

VNC=on
VNCIP=swvpl-spice
VNCTYPE=bridge
VNCTPL=VNCSECURE

QMP=on
QMPIP=swvpl-telnet
QMPTYPE=bridge

. ./DATA/VMMgr_VirtioNet
New_Network swvpl-prod01 "6|2a01:e0a:278:9833::|64" "2a01:e0a:278:9833::1|2a01:e0a:278:9833::FFFF:FFFF"
New_Network swvpl-main "6|2a01:e0a:278:9830::|64"  "2a01:e0a:278:9830::1|2a01:e0a:278:9830::FFFF:FFFF" 2a01:e0a:278:9830:82c5:f2ff:fe06:984f
NETWORKDEVICE="swvpl-main|1"

QEMU_TEMPLATE=LINUXBASE

###env for spice:
QEMU_AUDIO_DRV=spice
SPICE_DEBUG_ALLOW_MC=0
