#! /bin/bash
#
# script name: %%NAME%%
# autor: Sylvain Girod ( uubu at gmx dot fr )
# version: 0.02
# description: Template for %%NAME%%
GROUP=""
NAME="%%NAME%%"         # Unique Name
MEM="1"                 # Initial Mem Size, in GB
MAXMEM="1"               # OPTIONAL: Max Allowed mem (defaut: $MEM * 2)

### Disks ###

DISKPATH="/mnt/disks/%%NAME%%/"

## Note: At least 1 First disk is needed, Defaut: Virtio Disk, but if iscsi is defined and not virtio, use iscsi as first disk only
mVDISKSIZE=""             # First virtio Disk Size. Defaut: 2GB
mSDISKSIZE=""            # OPTIONAL: First iscsi Disk Size. Defaut: 2GB
## Additionnals Disks
sVDISKNUMBER=""           # OPTIONAL: number of additionals Virtio Disks
sVDISKSIZE=""             # OPTIONAL: Size for optionals Virtio Disks
sSDISKNUMBER=""           # OPTIONAL: number of additionals ISCSI Disks
sSDISKSIZE=""             # OPTIONAL: Size for optionals ISCSI Disks

## you can set individual disk in calling function manually:
# Set_Disk virtio 50G Disk1
# Set_Disk iscsi 20G /mnt/idisks/%%NAME%%-disk2

### choose Qemu machine Template:
New_Network swvpl-spice "6|2a01:e0a:278:9831::|64" "2a01:e0a:278:9831::10|2a01:e0a:278:9831::FFFF" 2a01:e0a:278:9831::1
SPICE=on
SPICEIP=swvpl-spice
SPICETYPE=bridge
SPICETPL=SPICESECURE

New_Network swvpl-telnet "6|2a01:e0a:278:9832::|64" "2a01:e0a:278:9832::10|2a01:e0a:278:9832::FFFF" 2a01:e0a:278:9832::1
TELNET=on
TELNETIP=swvpl-telnet
TELNETTYPE=bridge

VNC=on
VNCIP=swvpl-spice
VNCTYPE=bridge
VNCTPL=VNCSECURE

. ./DATA/VMMgr_VirtioNet
New_Network swvpl-prod01 "6|2a01:e0a:278:9833::|64" "2a01:e0a:278:9833::1|2a01:e0a:278:9833::FFFF:FFFF"
New_Network swvpl-main "6|2a01:e0a:278:9830::|64"  "2a01:e0a:278:9830::1|2a01:e0a:278:9830::FFFF:FFFF" 2a01:e0a:278:9830:82c5:f2ff:fe06:984f
NETWORKDEVICE="swvpl-prod01|2 swvpl-main|4"

QEMU_TEMPLATE=FAB

###env for spice:
EMU_AUDIO_DRV=spice
SPICE_DEBUG_ALLOW_MC=0
