#! /bin/bash
#
# script name: %%NAME%%
# autor: Sylvain Girod ( uubu at gmx dot fr )
# version: 0.02
# description: Template for %%NAME%%
GROUP=""
NAME="%%NAME%%"         # Unique Name
MEM="1"                 # Initial Mem Size, in GB
MAXMEM=""               # OPTIONAL: Max Allowed mem (defaut: $MEM * 2)

### Disks ###

DISKPATH="/mnt/disks/%%NAME%%/"

## Note: At least 1 First disk is needed, Defaut: Virtio Disk, but if iscsi is defined and not virtio, use iscsi as first disk only
VDISKSIZE=""             # First virtio Disk Size. Defaut: 2GB
SDISKSIZE=""            # OPTIONAL: First iscsi Disk Size. Defaut: 2GB
## Additionnals Disks
sVDISKNUMBER=""           # OPTIONAL: number of additionals Virtio Disks
sVDISKSIZE=""             # OPTIONAL: Size for optionals Virtio Disks
sSDISKNUMBER=""           # OPTIONAL: number of additionals ISCSI Disks
sSDISKSIZE=""             # OPTIONAL: Size for optionals ISCSI Disks

## you can set individual disk in calling function manually:
# Set_Disk virtio 50G Disk1
# Set_Disk iscsi 20G /mnt/idisks/%%NAME%%-disk2

### Network ###
# Set_NetDev <bridge> <number of taps>
# Set_NetDev swvpl-main 2
# Set_NetDev swvpl-admin 1


### choose Qemu machine Template:
QEMU_TEMPLATE=$LXBASE

###env for spice:
EMU_AUDIO_DRV=spice
SPICE_DEBUG_ALLOW_MC=0


#set_virtio_disk 1 50G 4G 1
#set_virtio_net swvpl-main 1
