#! /bin/bash
#
# script name: %%NAME%%
# Template Name: Live
# autor: Sylvain Girod ( uubu at gmx dot fr )
# version: 0.05
# description: Template for Live system
GROUP=""
NAME="%%NAME%%"         # Unique Name

CPU=CPUHOST
SMPTPL=SMPMAX
MEM="2"                 # Initial Mem Size, in GB
MAXMEM="2"              # OPTIONAL: Max Allowed mem (defaut: $MEM * 2)
BIOSTYPE="BIOS"


USEQEMUCONFIG="no"
#PERMANENTISO="https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/debian-live-10.2.0-amd64-kde.iso"
PERMANENTISO="https://download.fedoraproject.org/pub/fedora/linux/releases/31/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-31-1.9.iso"

New_Network VM-Bridge "4|10.98.98.0|24" "10.98.98.10|10.98.98.100" 10.98.98.1
TELNET=on
TELNETIP=VM-Bridge
TELNETTYPE=bridge

VNC=on
VNCIP=VM-Bridge
VNCTYPE=bridge
VNCTPL=VNCCLEAR

NETWORKDEVICE="VM-Bridge|1"

QEMU_TEMPLATE=LINUXBASE

###env for spice:
QEMU_AUDIO_DRV=spice
SPICE_DEBUG_ALLOW_MC=0
