#! /bin/bash
#
# script name: %%NAME%%
# autor: Sylvain Girod ( uubu at gmx dot fr )
# version: 0.05
# description: Template for Linux Base
#               1 CPU
#               1GB RAM
#               1HD 8G - Virtio-Disk
#               1 iface - Virtio-Net
#               Telnet and Spice
# ToDo: IPVER=4, VNC=off, qmp=off
GROUP=""
NAME="%%NAME%%"         # Unique Name
MEM="2"                 # Initial Mem Size, in GB
MAXMEM="2"              # OPTIONAL: Max Allowed mem (defaut: $MEM * 2)
BIOSTYPE="SECURE"

USEQEMUCONFIG="no"
PERMANENTISO="Fedora-Workstation-Live-x86_64-31-1.9.iso"

New_Network VM-Bridge "4|10.98.98.0|24" "10.98.98.10|10.98.98.100" 10.98.98.1
SPICEIPVER=4
SPICEMODE=plaintext
SPICE=on
SPICEIP=VM-Bridge
SPICETYPE=bridge
SPICETPL=SPICECLEAR

TELNETIPVER=4
TELNET=on
TELNETIP=VM-Bridge
TELNETTYPE=bridge

VNC=off
QMP=off

NETWORKDEVICE="VM-Bridge|1"

QEMU_TEMPLATE=LINUXBASE

###env for spice:
QEMU_AUDIO_DRV=spice
SPICE_DEBUG_ALLOW_MC=0
